### ISSUE TITLE
The script returns '-2147483648' in the TSV file if any value is a period ('.') in the Sample ID column of the VCF file.

### ISSUE THREAD

**Issue by razshaikh** [sigven/vcf2tsv#2]

**Comment by razshaikh** [comment]
### Input VCF File values
![Screenshot from 2022-01-11 12-43-49](https://user-images.githubusercontent.com/91732066/148897509-dd0f01a7-b820-404b-aa02-94d6c46098ce.png)

### Output TSV File values
![Screenshot from 2022-01-11 12-46-12](https://user-images.githubusercontent.com/91732066/148897821-3b309b5a-4e48-41af-9902-f8003dd83ac6.png)

**Comment by sigven** [comment]
Thanks @razshaikh for letting me know about this error! Could you share your VCF with me, so I can test and make sure that it can be fixed? It might be related to the underlying library (cyvcf), but I will check and see if I can fix it.

best,
Sigve

**Comment by razshaikh** [comment]
Hi @sigven, thank you for your response, Really appreciated.
Please find the sample VCF below:
[test_sample_run.zip](https://github.com/sigven/vcf2tsv/files/7845067/test_sample_run.zip)

**Comment by razshaikh** [comment]
Hi @sigven, any suggestions on how to solve this issue.

Thanks and Regards,
Razin

**Comment by sigven** [comment]
Hi @razshaikh,
I am working on it, sorry for the delayed response.

**Comment by razshaikh** [comment]
Hi @sigven, I understand you must be having other tasks on your hand. I really appreciated you looking into it. Thank you.
Best Wishes,
Razin

**Comment by sigven** [comment]
Hi again @razshaikh,

Been digging a bit, and it seems this matter is related to how [cyvcf2](https://github.com/brentp/cyvcf2) works. See [this related issue](https://github.com/brentp/cyvcf2/issues/195), for instance. 

Either way, I have now added a simple check for this in vcf2tsv (v0.3.6), which should fix the error you encountered. On another note, your test VCF was full of other strange formatting errors, so I had to change it quite a bit for a test run.

kind regards,
Sigve

**Comment by razshaikh** [comment]
Hi @sigven, 
Hope you are doing well.

Thank you for the update. I checked it, and it works for the 'GQ' values, but other values still has the same issue.

For example: the values in AD column, if any value is missing and has a period('.') instead, the latest script still replaces it with '-2147483648'. 

Let me know if you have any suggestions for it.

Thanks and regards,
Razin

**Comment by razshaikh** [comment]
Hi @sigven 

I have added a pull request, let me know if that makes sense.

Best wishes,
Razin
