### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by parnaljoshi** [sigven/vcf2tsv#8]
Hi, I am running vcf2tsv on an annotated VCF file, and getting this error:
```
> python3 vcf2tsv.py myhg38.hg38_multianno.vcf myhg38.hg38_multianno.tab
[W::vcf_parse] INFO '.' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'REVEL_rankscor' is not defined in the header, assuming Type=String
Segmentation fault
```
How can I resolve this? Any help would be greatly appreciated, thanks!

**Comment by sigven** [comment]
Hey,

Thanks for using the tool :-)

First:
I have just updated the tool (and even renamed it to `vcf2tsvpy`), so I would appreciate if you could install the latest [Conda-based](https://github.com/sigven/vcf2tsvpy#installation) version. Here, you use the tool as follows:

`vcf2tsvpy --input_vcf <example.vcf.gz> --out_tsv <example.tsv>`

The command you indicate above (`python3 vcf2tsvpy ..`) stems back to an old version of the tool.

Once you have installed the tool succesfully, I would also recommend that you, prior to running `vcf2tsvpy`, compress and index your input VCF (`myhg38.hg38_multianno.vcf`) with [bgzip + tabix](https://genome.ucsc.edu/goldenPath/help/vcf.html).

It might be that the cause of your error comes from errors in the input VCF, but I recommend you try the above first, and see what that gives you.

cheers,
Sigve
